Proceso  NOTAS
	Escribir " ESTIMADO ESTUDIANTE: INGRESE SUS NOTAS SEGUIDO DE LA TECLA <<ENTER>> PARA GENERAR SU PROMEDIO TOTAL. "
	Leer N1,N2,N3,N4,N5,N6,N7,N8
	PROMEDIO <-(N1+N2+N3+N4+N5+N6+N7+N8)/8
	Escribir " EL PROMEDIO FINAL ES: " , PROMEDIO
FinProceso
